**In This Notebook we will discuss NumPy Package , one of the most used python packages in data science and machine learning .**
![](https://en.wikipedia.org/wiki/NumPy#/media/File:NumPy_logo_2020.svg)

# Numpy Package Basics

## Table of Contents
<ul>
<li><a href="#intro">NumPy Arrays </a></li>
<li><a href="#intro2">Some NumPy Array Attributes and Methods </a></li>
<li><a href="#intro3">Indexing and Selection </a></li>
<li><a href="#intro4">NumPy Operations </a></li>
</ul>

first we import numpy package 

In [1]:
import numpy as np 

<a id="intro"></a>
# NumPy Arrays 

first we will discuss transforming of lists to numpy arrays 

In [2]:
# Simple Example : we will create list then transform it to Numpy array 
example_list = [1,2,3]
example_list

[1, 2, 3]

We can create a NumPy ndarray object by using the array() function

In [3]:
import numpy as np
example_list=[1,2,3]
np.array(example_list)

array([1, 2, 3])

we can try the same for multi dimensional data (nested lists) 

In [4]:
nested_list = [[1,2,3],[4,5,6]]
nested_list

[[1, 2, 3], [4, 5, 6]]

In [5]:
np.array(nested_list)

array([[1, 2, 3],
       [4, 5, 6]])

There are many ways to generate arrays in Numpy , we will discuss some of them 

In [6]:
# Use arange function to generate NumPy array that contain integers within specific range 
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Additional parameter to arange function (step Parameter)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
#generate vector of zeros 
np.zeros(3)

array([0., 0., 0.])

In [9]:
#generate 2D array of zeros 
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
#generate vector of ones 
np.ones(3)

array([1., 1., 1.])

In [11]:
#generate 2D array of ones
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# using linspace to generate elements with equal distance between them

np.linspace(0,15,4) # third parameter here is the number of elements you want 

array([ 0.,  5., 10., 15.])

In [13]:
# linspace can generate float numbers 
np.linspace(0,7,10)

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [14]:
# generate 2D matrix with eye function ( generate a matrix with 1 on diagonal , 0 otherwise )
#generate a 5 by 5 matrix 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Generate Random arrays 

In [15]:
# get array of random values from Uniform distribution 
np.random.rand(5)

array([0.06262018, 0.64255114, 0.60496887, 0.2181155 , 0.76101799])

In [16]:
# 2D array example 
np.random.rand(3,3)

array([[0.32306117, 0.34603372, 0.04888235],
       [0.81312233, 0.2606272 , 0.08206052],
       [0.33376556, 0.18183441, 0.67115702]])

In [17]:
# get array of random values from Standard Normal distribution 
np.random.randn(5)

array([-0.73444294,  1.35946113,  2.23592468,  1.71623001, -0.18015215])

In [18]:
np.random.randn(3,3)

array([[-1.53404325, -0.00516834,  0.26177576],
       [-1.17857983, -0.37824239, -1.38567258],
       [ 0.8378735 ,  0.17593042,  1.25499072]])

In [19]:
# generate random integer in specific range
np.random.randint(1,10)

8

In [20]:
# generate array of random integers in specific range
np.random.randint(1,15,4)

array([13,  5,  6,  7])

In [21]:
# generate 2D array of random integers in specific range
np.random.randint(1,20,(3,4))

array([[12, 14,  2,  8],
       [12,  2, 14,  6],
       [ 3,  8,  6, 13]])

problem of using random is that everytime you run the code you get different results , to solve this problem we will use 
seed function 

In [22]:
# Must give seed the same number everytime you run the code to ensure that your code is reproducible
np.random.seed(42)
# unlike the above cells , if you run this cells multiple times you'll get the same results 
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

<a id="intro2"></a>
# Some NumPy Array Attributes and Methods 

In [23]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# get the shape of array using shape attribute 
arr.shape

(10,)

In [25]:
# you can reshape the array to any other shape that have the same number of elements 
# example : arr have 10 elements can be reshaped to arr of shape (2,5) and arr of shape (5,2)
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
# if you want to reshape the array in its place you can reassign the above function to the variable arr 
arr = arr.reshape(2,5)

In [27]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [28]:
random_arr = np.random.randint(0,30,10)

In [29]:
random_arr

array([18, 22, 10, 10, 23, 20,  3,  7, 23,  2])

In [30]:
# get maximum of array 
random_arr.max()

23

In [31]:
# get index of the maximum value in array 
random_arr.argmax()

4

In [32]:
# get minimum value in array 
random_arr.min()

2

In [33]:
# get index of minimum value in array 
random_arr.argmin()

9

In [34]:
# get the datatype of your array 
random_arr.dtype

dtype('int64')

In [35]:
# repeat given element (or elements) for fixed number of times 
np.repeat(5,3)

array([5, 5, 5])

<a id="intro3"></a>
# Indexing and Selection 

In [36]:
arr = np.arange(0,11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
# Select a single value 
arr[3]

3

In [39]:
# Indexing start with 0 , so first element will be in arr[0]
arr[0]

0

In [40]:
# Select multiple values from array 
arr[1:4]

array([1, 2, 3])

In [41]:
# Select from beginning of array to specific index 
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [42]:
# Select from specific index to the last element of array 
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
# Assign single value 
arr[2] = -1 

In [44]:
arr

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
# Assign value to multiple array indexes
arr[2:5] = 100 

In [46]:
arr

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
# let's try slicing 
slice_arr = arr[1:5]

In [48]:
slice_arr

array([  1, 100, 100, 100])

In [49]:
# Assign values to all elements of numpy array 
slice_arr[:] = 10

In [50]:
slice_arr

array([10, 10, 10, 10])

you will notice that the update in slice_arr affects the values in arr because both of them point to the same array

In [51]:
arr

array([ 0, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

To overcome this problem you can get a copy of arr in slice_arr and then update the values 

In [52]:
slice_arr = arr[1:5].copy()

In [53]:
slice_arr[:] = -1 

In [54]:
slice_arr

array([-1, -1, -1, -1])

In [55]:
arr

array([ 0, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

you can notice that this time arr didn't get the update we do in slice_arr

In [56]:
# 2D array example
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [57]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr_2d.shape

(3, 3)

In [59]:
# get the third row in arr_2d

arr_2d[2]

array([7, 8, 9])

In [60]:
# to access single value in 2d array you should give 2 indexes , 1 for row and 1 for column 

arr_2d[1][1]

5

In [61]:
# another way to get single value 

arr_2d[1,1]

5

In [62]:
# get more than 1 row 

arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
# get more than 1 row with specific columns included 

arr_2d[:2,1]

array([2, 5])

Conditional Selection : select values with specific conditions 

In [64]:
arr = np.arange(1,15)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
# Try simple condition 
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [67]:
# let's select elements based on the previous condition , it should return elements which match the condition only 

condition = arr>5
arr[condition]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
# another example 
arr[arr>10]

array([11, 12, 13, 14])

<a id="intro4"></a>
# NumPy Operations

In [69]:
arr = np.arange(0,10)

In [70]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
# adding number to array 
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
# subtracting number to array 
arr - 3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [73]:
# multiply array by itself 
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [74]:
# minus array from itself 
arr - arr 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
# square root of array 
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [76]:
# sin of array 
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [77]:
# log of array 
np.log(arr)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

Summary functions on array 

In [78]:
# get sum of array 
arr.sum()

45

In [79]:
# get mean of array 
arr.mean()

4.5

In [80]:
# variance of array 
arr.var()

8.25

In [81]:
# standard deviation of array 
arr.std()

2.8722813232690143

In [82]:
arr_2d = np.arange(0,25).reshape(5,5)

In [83]:
arr_2d.shape

(5, 5)

In [84]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [85]:
# total sum of array 
arr_2d.sum()

300

In [86]:
# sum of each row in the array 
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [87]:
# sum of each column in the array 
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])